system:
    front_group:
        content:
            tree_root:
                location_id: 77


        location_view:
            full:
                page:
                    template: PadMayaBundle:page:full.html.twig
                    match:
                        Identifier\ContentType: page
            container:
                slider_full:
                    template: PadMayaBundle:container:slider_full.html.twig
                    match:
                        Identifier\ContentType: slider_full
                slider_parallax:
                    template: PadMayaBundle:container:slider_parallax.html.twig
                    match:
                        Identifier\ContentType: slider_parallax
                parallax_full:
                    template: PadMayaBundle:container:parallax_full.html.twig
                    match:
                        Identifier\ContentType: parallax_full
                standard:
                    template: PadMayaBundle:container:standard.html.twig
                    match:
                        Identifier\ContentType: standard
                part_list_page:
                    template: PadMayaBundle:container:list_page.html.twig
                    match:
                        Identifier\ContentType: part_list_page
            item:
                image:
                    template: PadMayaBundle:item:image.html.twig
                    match:
                        Identifier\ContentType: image
            slide:
                image:
                    template: PadMayaBundle:slide:image.html.twig
                    match:
                        Identifier\ContentType: image

            menu:
                page:
                    template: PadMayaBundle:global:menu/page.html.twig
                    match:
                        Identifier\ContentType: page
